### ISSUE TITLE
chb - mit ANNOTATION FILE

### ISSUE THREAD

**Issue by RenukaKhati** [SMorettini/CNNs-on-CHB-MIT#1]
Unable to download chb - mit annotation files. Please help me out

**Comment by SMorettini** [comment]
What are you meaning for "annotation file"?

**Comment by RenukaKhati** [comment]
annotation file indicating the start and end of the seizure activity.

**Comment by RenukaKhati** [comment]
> annotation file indicating the start and end of the seizure activity.

yes I got the file having seizure duration, but how to identify that in which channel seizure was present while taking the EEG recording of patient.

**Comment by SMorettini** [comment]
> how to identify that in which channel seizure was present

There is no file specifying that. I suppose that when a seizure in all the channel the consequences are visible. Usually the seizure start from a point in the brain(this is was the network is try to find to predict in advance the seizure) so only a few channel can reveal the incoming of the seizure, than it spread all over the brain.
For more information I suggest you to read the paper that we tried to replicate the approach: [Truong, Nhan Duy, et al. "Convolutional neural networks for seizure prediction using intracranial and scalp electroencephalogram." Neural Networks 105 (2018): 104-111](https://www.sciencedirect.com/science/article/pii/S0893608018301485)

**Comment by RenukaKhati** [comment]
> > how to identify that in which channel seizure was present
> 
> There is no file specifying that. I suppose that when a seizure in all the channel the consequences are visible. Usually the seizure start from a point in the brain(this is was the network is try to find to predict in advance the seizure) so only a few channel can reveal the incoming of the seizure, than it spread all over the brain.
> For more information I suggest you to read the paper that we tried to replicate the approach: [Truong, Nhan Duy, et al. "Convolutional neural networks for seizure prediction using intracranial and scalp electroencephalogram." Neural Networks 105 (2018): 104-111](https://www.sciencedirect.com/science/article/pii/S0893608018301485)

okay thanks.
