### ISSUE TITLE
threhold

### ISSUE THREAD

**Issue by wangyumo85** [SMorettini/CNNs-on-CHB-MIT#11]
threhold 中的 secondsInterictalInTest 的数值是怎么得到的

**Comment by SMorettini** [comment]
Could you translate your message in English? :)

**Comment by wangyumo85** [comment]
How to get the value in threshold

**Comment by SMorettini** [comment]
I'm not sure what you are asking, can you be more specific on your question?

**Comment by ZH-UCAS** [comment]
why threshold=[0.6,0.8, 0.4, 0.3,0.3] 
why not threshold=[0.5,0.5, 0.5, 0.5,0.5]

**Comment by SMorettini** [comment]
There is one CNN for each patient so each CNN is trained on different data. It means that I had to use differents thresholds. The threshold was computed using the training data to maximize the correct classifications.

**Comment by ZH-UCAS** [comment]
thanks
