### ISSUE TITLE
CNN's training data

### ISSUE THREAD

**Issue by Afef00** [SMorettini/CNNs-on-CHB-MIT#2]
Actually I have some questions about your code:
1- In the training why did you choose that it be be for each patient apart I mean why didn't you collect the spectrograms for all patients and use it as input for CNN. . 
2- How could I know the number of the training data used?

**Comment by SMorettini** [comment]
> In the training why did you choose that it be be for each patient apart I mean why didn't you collect the spectrograms for all patients and use it as input for CNN.

Because each patient has his characteristic so it's necessary a specific model for each patient.

>  How could I know the number of the training data used?

I'm not understanding the question, could you explain it better?

**Comment by Afef00** [comment]
I mean the number of  training samples(X-train) used as inputs to the CNN model. If I want to load these samples as well as Y-train how can I do that? 
Thank You!

**Comment by SMorettini** [comment]
> I mean the number of training samples(X-train) used as inputs to the CNN model

I don't know the actual number of training samples but it's possible to recover them from the following table. 

![table](https://user-images.githubusercontent.com/7838869/66990886-55ca7300-f0c7-11e9-80f9-2ec02269eb23.PNG)

For example patient 1 has 14.49 hours of interictal data. Each sample contain 30 seconds of data so 14.49 hours = 53340 seconds / 30seconds=1778 samples for interictal data. The preictal are almost the same number so in total for patient 1 almost 3500 sampled where used.
The training set was 75% of the total set of samples so I used almost 2625 samples for training.

> If I want to load these samples as well as Y-train how can I do that?

You have to create the spectograms, [here](https://github.com/MesSem/CNNs-on-CHB-MIT/tree/e1e7a19ded971d521054fd3a063a7943f9c53336#running) more information are provided.
