### ISSUE TITLE
What is the meaning of S variable?

### ISSUE THREAD

**Issue by ducnx** [SMorettini/CNNs-on-CHB-MIT#4]
Question is same as title, what is the meaning of S variable at the referenced line?
https://github.com/MesSem/CNNs-on-CHB-MIT/blob/e1e7a19ded971d521054fd3a063a7943f9c53336/DataserToSpectogram.py#L372

**Comment by ducnx** [comment]
Sorry, I actually read the paper but I don't understand how you come up with that value of S.
Can you please explain?

**Comment by SMorettini** [comment]
S is the amount of seconds use for slide the window for the creation of a balanced dataset. 
The preictal data are many less than the interictal data. To balance the data, in the paper, they decided to create "syntetic" data by overlapping the windows. So for interictal the windows slide for the size of the window, instead for preictal data the windows slide for a smaller range of seconds. 
https://github.com/MesSem/CNNs-on-CHB-MIT/blob/e1e7a19ded971d521054fd3a063a7943f9c53336/DataserToSpectogram.py#L124-L130

![CHBMIT_S](https://user-images.githubusercontent.com/7838869/66989280-5d3c4d00-f0c4-11e9-909c-9cbb1ddeb333.PNG)
I put this image to help you understand. I don't know if my explanation is clear, if you don't understand I'll try to explain in a better way.
