### ISSUE TITLE
What does the "real preictal" mean?

### ISSUE THREAD

**Issue by yuweiDu** [SMorettini/CNNs-on-CHB-MIT#6]
What does the "real preictal" mean? I didn't find anything about it in the paper.When you train the CNN,what data will be used? preictal data or real preictal data ?I am really confused. Thank you

**Comment by SMorettini** [comment]
In the code we used the term "real preictal" to identify the data obtained from the real data of the dataset, instead we use "preictal" data to identify syntetic data. In the image the white rectangle are the "real preictal", the grey are the "preictal" data, so syntetic data.

![image](https://user-images.githubusercontent.com/7838869/70607818-6e569580-1bff-11ea-9697-42e4324f8e55.png)


So we use the preictal data(synteitc data) to train the network. We choose that to have a balanced dataset. Instead we use the "real preictal" for testing the network.

> I didn't find anything about it in the paper

We only tried to replicate the paper, we didn't write it so sometimes we use different words or terms to describe part of the project.
