### ISSUE TITLE
About generating spectrogram shapes

### ISSUE THREAD

**Issue by Lin-xuejuan-an** [SMorettini/CNNs-on-CHB-MIT#9]
Hello @ritwikmishra ,
          Thank you very much for providing such excellent code, I have a question to ask you .
          I check the spectrogram generated in the first part of the code and get ”shape: (50, 21, 59, 114)“, what should I do to make the shape generate three-dimensional ？I would be grateful if you could provide some suggestions and look forward to receiving your reply .

**Comment by VincenzoNucci** [comment]
Hi @Lin-xuejuan-an. If you mean to obtain arrays of shape (21,59,114) note that the first dimension refers to the batch size, so simply taking elements in the first axis will give you three-dimensional spectrograms made only by channels, height and width
